scopes:
    statut:
        label: Etendue
        modelClass: DigArt\Spectacles\Models\PublicationEtendue
        conditions: etendue_id in (:filtered)
        nameFrom: designation
    saison:
        label: Auteur
        modelClass: \Backend\Models\User
        conditions: admin_id in (:filtered)
        nameFrom: full_name
    is_actif:
        label: Actif
        type: switch
        default: 0
        conditions:
            - is_actif <> true
            - is_actif = true