title: Publications
modelClass: Digart\spectacles\Models\Publication
list: $/digart/spectacles/models/publication/columns.yaml
recordUrl: 'digart/spectacles/publications/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: debut
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
filter: config_filter.yaml
