list: $/digart/spectacles/models/categorie/columns.yaml
modelClass: Digart\spectacles\Models\Categorie
title: Categories
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'digart/spectacles/categories/update/:id'
