list: $/digart/spectacles/models/agent/columns.yaml
modelClass: Digart\spectacles\Models\Agent
title: Agents
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'digart/spectacles/agents/update/:id'
