plugin:
    name: 'digart.spectacles::lang.plugin.name'
    description: 'digart.spectacles::lang.plugin.description'
    author: digart
    icon: oc-icon-music
    homepage: 'https://www.digital-artisan.ch'
permissions:
    digart.spectacles.saisons:
        tab: 'CTTR - Gestion des spectacles'
        label: 'Gère les saisons'
    digart.spectacles.spectacles:
        tab: 'CTTR - Gestion des spectacles'
        label: 'Gère les spectacles'
    digart.spectacles.institutions:
        tab: 'CTTR - Paramètres'
        label: 'Gère les institutions'
    digart.spectacles.genres:
        tab: 'CTTR - Gestion des spectacles'
        label: 'Gère les genres de spectacles'
    digart.spectacles.lieux:
        tab: 'CTTR - Paramètres'
        label: 'Gère les lieux des spectacles'
    digart.spectacles.statuts:
        tab: 'CTTR - Paramètres'
        label: 'Gère les statuts des spectacles'
    digart.spectacles.artistes:
        tab: 'CTTR - Gestion des spectacles'
        label: 'Gère les artistes'
    digart.spectacles.agents:
        tab: 'CTTR - Gestion des spectacles'
        label: 'Gère les agents des artistes'
    digart.spectacles.categories:
        tab: 'CTTR - Gestion des spectacles'
        label: 'Gère les catégories de spectacles'
    digart.spectacles.souvenirs:
        tab: 'CTTR - Gestion des spectacles'
        label: 'Gère les souvenirs (photos) des spectacles'
    digart.spectacles.spectacles.preview:
        tab: 'CTTR - Gestion des spectacles'
        label: 'Peut voir les spectacles "brouillon" dans le frontend'
    digart.spectacles.protocoles:
        tab: 'CTTR - Gestion des spectacles'
        label: 'Gère les protocoles des spectacles'
    digart.spectacles.pstatuts:
        tab: 'CTTR - Paramètres'
        label: 'Gère les statuts des protocoles'
    digart.spectacles.pgenres:
        tab: 'CTTR - Paramètres'
        label: 'Gère les genres de protocoles'
    digart.spectacles.publications:
        tab: 'CTTR - Gestion de la communication'
        label: 'Gère les entrées des publications'
    digart.spectacles.publications.etendues:
        tab: 'CTTR - Gestion de la communication'
        label: 'Gère l''étendue des publications des publications'
    digart.spectacles.web:
        tab: 'CTTR - Gestion de la communication'
        label: 'Gère les textes statiques du site web'
    digart.spectacles.abonnements:
        tab: 'CTTR - Paramètres'
        label: 'Gère les billets et les abonnements de l''institution'
    digart.spectacles.team:
        tab: 'CTTR - Paramètres'
        label: 'Gère l''équipe pour la partie publique du site'
    digart.spectacles.locations:
        tab: 'CTTR - Gestion'
        label: 'Gère les locations de la salle'
    digart.spectacles.locations.dates:
        tab: 'CTTR - Gestion'
        label: 'Gère les dates des locations'
navigation:
    gestion:
        label: 'Gestion CTTR'
        url: digart/spectacles/locations
        icon: icon-dot-circle-o
        sideMenu:
            locations:
                label: 'Location salle'
                url: digart/spectacles/locations
                icon: icon-building-o
                permissions:
                    - digart.spectacles.locations
    spectacles:
        label: Spectacles
        url: digart/spectacles/spectacles
        icon: icon-microphone
        sideMenu:
            spectacles:
                label: Spectacles
                url: digart/spectacles/spectacles
                icon: icon-music
            side-menu-item:
                label: Saisons
                url: digart/spectacles/saisons
                icon: icon-calendar-o
                permissions:
                    - digart.spectacles.saisons
            categories:
                label: Catégories
                url: digart/spectacles/categories
                icon: icon-tag
            genres:
                label: Genres
                url: digart/spectacles/genres
                icon: icon-wechat
            artistes:
                label: Artistes
                url: digart/spectacles/artistes
                icon: icon-user
            agents:
                label: Agents
                url: digart/spectacles/agents
                icon: icon-dollar
    communication:
        label: 'Communication CTTR'
        url: digart/spectacles/publications
        icon: icon-newspaper-o
        permissions:
            - digart.spectacles.publications.etendues
            - digart.spectacles.publications
            - digart.spectacles.web
        sideMenu:
            publications:
                label: Publications
                url: digart/spectacles/publications
                icon: icon-newspaper-o
                permissions:
                    - digart.spectacles.publications
            etendue-publication:
                label: 'Etendues de publications'
                url: digart/spectacles/publicationsetendues
                icon: icon-road
                permissions:
                    - digart.spectacles.publications.etendues
            frontend:
                label: 'Contenu web'
                url: digart/spectacles/webs
                icon: icon-sitemap
                permissions:
                    - digart.spectacles.web
    parametres-cttr:
        label: 'Paramètres CTTR'
        url: digart/spectacles/institutions
        icon: icon-wrench
        sideMenu:
            institutions:
                label: Institutions
                url: digart/spectacles/institutions
                icon: icon-institution
            lieux:
                label: Lieux
                url: digart/spectacles/lieux
                icon: icon-map-marker
            statuts:
                label: 'Statuts spectacles'
                url: digart/spectacles/statuts
                icon: icon-dashboard
            statuts-protocoles:
                label: 'Statuts de protocoles'
                url: digart/spectacles/protocolesstatuts
                icon: icon-dashboard
                permissions:
                    - pro
            genres-protocoles:
                label: 'Genres des protocoles'
                url: digart/spectacles/protocolesgenres
                icon: icon-puzzle-piece
            abonnements:
                label: 'Abonnements et groupes'
                url: digart/spectacles/abonnementsgroupes
                icon: icon-ticket
                permissions:
                    - digart.spectacles.abonnements
            team:
                label: Equipe
                url: digart/spectacles/teams
                icon: icon-group
                permissions:
                    - digart.spectacles.team
