plugin:
    name: 'digart.spectacles::lang.plugin.name'
    description: 'digart.spectacles::lang.plugin.description'
    author: digart
    icon: oc-icon-music
    homepage: 'https://www.digital-artisan.ch'
permissions:
    digart.spectacles.saisons:
        tab: 'TDR - Gestion des spectacles'
        label: 'Gère les saisons'
    digart.spectacles.spectacles:
        tab: 'TDR - Gestion des spectacles'
        label: 'Gère les spectacles'
    digart.spectacles.institutions:
        tab: 'TDR - Gestion des paramètres'
        label: 'Gère les institutions'
    digart.spectacles.genres:
        tab: 'TDR - Gestion des spectacles'
        label: 'Gère les genres de spectacles'
    digart.spectacles.lieux:
        tab: 'TDR - Gestion des paramètres'
        label: 'Gère les lieux des spectacles'
    digart.spectacles.statuts:
        tab: 'TDR - Gestion des paramètres'
        label: 'Gère les statuts des spectacles'
    digart.spectacles.artistes:
        tab: 'TDR - Gestion des spectacles'
        label: 'Gère les artistes'
    digart.spectacles.agents:
        tab: 'TDR - Gestion des spectacles'
        label: 'Gère les agents des artistes'
    digart.spectacles.categories:
        tab: 'TDR - Gestion des spectacles'
        label: 'Gère les catégories de spectacles'
    digart.spectacles.souvenirs:
        tab: 'TDR - Gestion des spectacles'
        label: 'Gère les souvenirs (photos) des spectacles'
    digart.spectacles.spectacles.preview:
        tab: 'TDR - Gestion des spectacles'
        label: 'Peut voir les spectacles "brouillon" dans le frontend'
    digart.spectacles.protocoles:
        tab: 'TDR - Gestion des spectacles'
        label: 'Gère les protocoles des spectacles'
    digart.spectacles.pstatuts:
        tab: 'TDR - Gestion des paramètres'
        label: 'Gère les statuts des protocoles'
    digart.spectacles.pgenres:
        tab: 'TDR - Gestion des paramètres'
        label: 'Gère les genres de protocoles'
    digart.spectacles.blog:
        tab: 'TDR - Gestion de la communication'
        label: 'Gère les entrées du blog'
    digart.spectacles.blog.etendue:
        tab: 'TDR - Gestion de la communication'
        label: 'Gère l''étendue des publications du blog'
navigation:
    spectacles:
        label: Spectacles
        url: digart/spectacles/spectacles
        icon: icon-microphone
        sideMenu:
            spectacles:
                label: Spectacles
                url: digart/spectacles/spectacles
                icon: icon-music
            side-menu-item:
                label: Saisons
                url: digart/spectacles/saisons
                icon: icon-calendar-o
                permissions:
                    - digart.spectacles.saisons
            categories:
                label: Catégories
                url: digart/spectacles/categories
                icon: icon-tag
            genres:
                label: Genres
                url: digart/spectacles/genres
                icon: icon-wechat
            artistes:
                label: Artistes
                url: digart/spectacles/artistes
                icon: icon-user
            agents:
                label: Agents
                url: digart/spectacles/agents
                icon: icon-dollar
    parametres-cttr:
        label: 'Paramètres CTTR'
        url: digart/spectacles/institutions
        icon: icon-wrench
        sideMenu:
            institutions:
                label: Institutions
                url: digart/spectacles/institutions
                icon: icon-institution
            lieux:
                label: Lieux
                url: digart/spectacles/lieux
                icon: icon-map-marker
            statuts:
                label: 'Statuts spectacles'
                url: digart/spectacles/statuts
                icon: icon-dashboard
            statuts-protocoles:
                label: 'Statuts de protocoles'
                url: digart/spectacles/protocolesstatuts
                icon: icon-dashboard
                permissions:
                    - pro
            genres-protocoles:
                label: 'Genres des protocoles'
                url: digart/spectacles/protocolesgenres
                icon: icon-puzzle-piece
    news-cttr:
        label: 'Communication CTTR'
        url: digart/spectacles/blogs
        icon: icon-newspaper-o
        sideMenu:
            actualites:
                label: Blog
                url: digart/spectacles/blogs
                icon: icon-newspaper-o
                permissions:
                    - digart.spectacles.blog
            blog-etendue:
                label: 'Etendue du blog'
                url: digart/spectacles/blogetendues
                icon: icon-road
                permissions:
                    - digart.spectacles.blog.etendue
