title: 'Contenu web'
modelClass: Digart\spectacles\Models\Web
list: $/digart/spectacles/models/web/columns.yaml
recordUrl: 'digart/spectacles/webs/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
