title: Tiers
modelClass: Digart\spectacles\Models\Tiers
list: $/digart/spectacles/models/tiers/columns.yaml
recordUrl: 'digart/spectacles/tiers/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
