title: Spectacles
modelClass: Digart\spectacles\Models\Spectacle
list: $/digart/spectacles/models/spectacle/columns.yaml
recordUrl: 'digart/spectacles/spectacles/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
filter: config_filter.yaml