scopes:
    statut:
        label: Statuts spectacles
        modelClass: DigArt\Spectacles\Models\Statut
        conditions: statut_id in (:filtered)
        nameFrom: designation
    saison:
        label: Saisons
        modelClass: DigArt\Spectacles\Models\Saison
        conditions: saison_id in (:filtered)
        nameFrom: designation
        options: getSaisonOptions
    artistes:
        label: Artistes
        modelClass: DigArt\Spectacles\Models\Artiste
        conditions: id in (select spectacle_id from digart_spectacles_spect_art where artiste_id in (:filtered))
        nameFrom: designation
        options: trier
    categorie:
        label: Catégorie
        modelClass: DigArt\Spectacles\Models\Categorie
        conditions: categorie_id in (:filtered)
        nameFrom: designation
    genres:
        label: Genres
        modelClass: DigArt\Spectacles\Models\Genre
        conditions: id in (select spectacle_id from digart_spectacles_spect_genr where genre_id in (:filtered))
        nameFrom: designation
    administrateur:
        label: Programmateur
        modelClass: \Backend\Models\User
        conditions: admin_id in (:filtered)
        nameFrom: full_name   
    statut_representation:
        label: Statuts représentations
        modelClass: DigArt\Spectacles\Models\Statut
        conditions: id in (select spectacle_id from digart_spectacles_repres where statut_id in (:filtered))
        nameFrom: designation             
    debut:
        label: Période représentations
        type: daterange
        #conditions: fin >= ':after' AND fin <= ':before'         
        conditions: id in (select spectacle_id from digart_spectacles_repres where debut >= CONVERT(':afterDate', DATETIME) AND debut <= CONVERT(':beforeDate', DATETIME) )       