title: Locations
modelClass: Digart\spectacles\Models\Location
list: $/digart/spectacles/models/location/columns.yaml
recordUrl: 'digart/spectacles/locations/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
