title: Saisons
modelClass: Digart\spectacles\Models\Saison
list: $/digart/spectacles/models/saison/columns.yaml
recordUrl: 'digart/spectacles/saisons/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: debut
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
