list: $/digart/spectacles/models/artiste/columns.yaml
modelClass: Digart\spectacles\Models\Artiste
title: Artistes
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'digart/spectacles/artistes/update/:id'
