name: Artistes
form: $/digart/spectacles/models/artiste/fields.yaml
modelClass: Digart\spectacles\Models\Artiste
defaultRedirect: digart/spectacles/artistes
create:
    redirect: 'digart/spectacles/artistes/update/:id'
    redirectClose: digart/spectacles/artistes
update:
    redirect: digart/spectacles/artistes
    redirectClose: digart/spectacles/artistes
